<?php
/* THIS IS A GENERATED FILE. DO NOT EDIT DIRECTLY. */
$optimizer_i18n_strings = array(
	__( 'Cancel', 'sg-cachepress' ),
	__( 'Confirm', 'sg-cachepress' ),
	__( 'Get the Most of This Plugin', 'sg-cachepress' ),
	__( 'Collect technical data about my installation. The data will be used to make sure that the plugin(s) works seamlessly on the widest possible range of WordPress sites. (A full list of the data to be collected can be found {{link}}here{{/link}}).', 'sg-cachepress' ),
	__( 'Send me occasional emails about updates, special offers and new features from SiteGround.', 'sg-cachepress' ),
	__( 'Feature Unavailable', 'sg-cachepress' ),
	__( 'Enable', 'sg-cachepress' ),
	__( 'Recommended', 'sg-cachepress' ),
	__( 'Select one or more', 'sg-cachepress' ),
	__( 'Cancel', 'sg-cachepress' ),
	__( 'Confirm', 'sg-cachepress' ),
	__( 'SiteGround Optimizer', 'sg-cachepress' ),
	__( 'Get the best performance for your WordPress website with our top-rated optimization plugin. The SiteGround Optimizer handles caching better than ever and provides a number of environment, media and frontend optimizations for a blazing-fast loading.', 'sg-cachepress' ),
	__( 'SiteGround Optimizer - Caching', 'sg-cachepress' ),
	__( 'Caching is essential for speeding up your website. With our Dynamic Caching enabled all non-static resources of your website are cached to prevent unnecessary database queries and page loading, effectively decreasing the loading sped and TTFB (time to first byte) of your website.', 'sg-cachepress' ),
	__( 'SiteGround Optimizer - Environment', 'sg-cachepress' ),
	__( 'Create a safer and faster experience for your users with an optimized environment - decrease the CPU usage by modifying the WordPress Heartbeat API; Pre-Fetch External domains to decrease loading time for third-party domains content; Schedule Database Maintenance to keep your databases clean and fast, and more.', 'sg-cachepress' ),
	__( 'SiteGround Optimizer - Frontend Optimization', 'sg-cachepress' ),
	__( 'Frontend optimizations can significantly decrease loading speed with a variety of changes that reduce the size of scripts as well as the number of characters used.', 'sg-cachepress' ),
	__( 'SiteGround Optimizer - Speed Test', 'sg-cachepress' ),
	__( 'Test your website loading speed with Google PageSpeed. The detailed audits will cover more than 20 areas in terms of how your website performs. Additionally, tips and tricks on improving your score will be provided if an optimization opportunity occurs.', 'sg-cachepress' ),
	__( 'SiteGround Optimizer - Media', 'sg-cachepress' ),
	__( 'Image optimization is one of the fundamentals of improving site speed. With image compression, lazy load, and WebP enabled, your site loading speed will be reduced significantly. Additionally, the space your images occupy may also decrease, optimizing your disk space usage.', 'sg-cachepress' ),
	__( 'Error', 'sg-cachepress' ),
	__( 'Success', 'sg-cachepress' ),
	__( 'This feature only works if you have Dynamic Caching enabled. To start using this feature, enable Dynamic Caching first.', 'sg-cachepress' ),
	__( 'Caching Types', 'sg-cachepress' ),
	__( 'Caching Settings', 'sg-cachepress' ),
	__( 'Automatic Purge', 'sg-cachepress' ),
	__( 'Perform a smart cache purge based on events happening on your WordPress site.', 'sg-cachepress' ),
	__( 'When clearing the cache - purge the WordPress API cache too.', 'sg-cachepress' ),
	__( 'Automatic Purge Caching only works if you have Dynamic Caching enabled. To start using this feature, please enable Dynamic Caching first.', 'sg-cachepress' ),
	__( 'Automatic Purge Caching only works if you have File-based Caching enabled. To start using this feature, please enable File-based Caching first.', 'sg-cachepress' ),
	__( 'Manual Cache Purge', 'sg-cachepress' ),
	__( "Purge the cache of your website manually. You can use this option when you're modifying new content and don't have automatic purge enabled to make sure that old cached is purged right away", 'sg-cachepress' ),
	__( 'Purge Cache', 'sg-cachepress' ),
	__( 'Exclude URLs from Caching', 'sg-cachepress' ),
	__( 'Use this feature if you want to exclude certain parts of your website from being cached and keep them dynamic. You can exclude full or partial URLs using "*" as a wildcard. E.g. www.site.com/parent-page/* will exclude all sub-pages of "parent-page".', 'sg-cachepress' ),
	__( '%(number)s URLs', 'sg-cachepress' ),
	__( 'Exclude Post Types from Caching', 'sg-cachepress' ),
	__( "You can exclude certain post types from being cached. This is useful if you have sensitive or often changing post types that you don't want to cache but still want to benefit from caching for the rest of your site.", 'sg-cachepress' ),
	__( '%(number)s post types', 'sg-cachepress' ),
	__( 'Test URL Caching Status', 'sg-cachepress' ),
	__( 'Review the caching status of specific URLs. Use this functionality to verify whether excluded URLs are working as expected.', 'sg-cachepress' ),
	__( 'Test', 'sg-cachepress' ),
	__( 'Exclude URLs from Caching', 'sg-cachepress' ),
	__( 'Invalid URL', 'sg-cachepress' ),
	__( 'Exclude Post Types from Caching', 'sg-cachepress' ),
	__( 'Browser-specific Caching', 'sg-cachepress' ),
	__( "Generate caching separately for different browsers. Enable this feature only if you're experiencing issues with plugins generating mobile versions of your website or other similar functionality. {{strong}}This feature significantly lowers caching efficiency.{{/strong}}", 'sg-cachepress' ),
	__( 'Browser-specific Caching only works if you have Dynamic Caching enabled. To start using this feature, please enable Dynamic Caching first.', 'sg-cachepress' ),
	__( 'Browser-specific Caching only works if you have File-based Caching enabled. To start using this feature, please enable File-based Caching first.', 'sg-cachepress' ),
	__( 'Cloudflare Full Page Caching', 'sg-cachepress' ),
	__( 'This option will enable full-page caching on your Cloudflare CDN edges. This will reduce the load on your SiteGround server and improve the loading speeds of your pages because by default Cloudflare will cache only your static resources.', 'sg-cachepress' ),
	__( 'Authenticate with Cloudflare', 'sg-cachepress' ),
	__( 'Your Cloudflare account may have page rules set that might affect the work of our integration. SiteGround Optimizer will delete all Page Rules and replace that functionality with Cloudflare workers. Note, that Cloudflare workers are free up to 100 000 requests a day and if you go past that number you may need to upgrade your account in order to keep using this functionality.', 'sg-cachepress' ),
	__( 'Email used with Cloudflare', 'sg-cachepress' ),
	__( 'Get the Cloudflare Global Api Key from {{link}}here{{/link}}', 'sg-cachepress' ),
	__( 'Disable full page caching ', 'sg-cachepress' ),
	__( 'This means that if you want to enable Full page caching again, you will have to authenticate anew.', 'sg-cachepress' ),
	__( 'Do you wish to proceed?', 'sg-cachepress' ),
	__( 'I want to deauthenticate from Cloudflare.', 'sg-cachepress' ),
	__( 'Dynamic Caching', 'sg-cachepress' ),
	__( "Store your content in the server's memory for a faster access with full-page caching solution powered by NGINX. Having Dynamic Cache is essential for speeding up your website.", 'sg-cachepress' ),
	__( 'File-based Caching only works if you have Dynamic Caching enabled. To start using this feature, please enable Dynamic Caching first.', 'sg-cachepress' ),
	__( 'File-Based Caching', 'sg-cachepress' ),
	__( 'With file-based caching enabled we will create static HTML versions of your website which will be served to future visitors. The files are stored in the browser memory.', 'sg-cachepress' ),
	__( 'Configure', 'sg-cachepress' ),
	__( 'Configure File-Based Caching', 'sg-cachepress' ),
	__( 'Manage the settings of your file-based caching to ensure optimal performance.', 'sg-cachepress' ),
	__( 'Clean up interval', 'sg-cachepress' ),
	__( ' Preheat cache', 'sg-cachepress' ),
	__( 'When Preheating is enabled, our system will reload the cache once it is purged after content update in order to serve the fastest possible results to your real visitors.', 'sg-cachepress' ),
	__( 'Logged-in users cache', 'sg-cachepress' ),
	__( 'By default, we do not cache content for logged in users. Once Logged In Cache is enabled, we will store separate caches for each user. Note, that if you have many users, the size of the stored cache may be increased.', 'sg-cachepress' ),
	__( 'Memcached', 'sg-cachepress' ),
	__( 'Powerful object caching for your site. Memcached stores frequently executed queries to your databases and then reuses them for better performance.', 'sg-cachepress' ),
	__( 'Enabled', 'sg-cachepress' ),
	__( 'Disabled', 'sg-cachepress' ),
	__( 'Dynamic Caching Status', 'sg-cachepress' ),
	__( 'Other Optimizations', 'sg-cachepress' ),
	__( 'Important Notifications', 'sg-cachepress' ),
	__( 'Rate Us', 'sg-cachepress' ),
	__( 'Thank you for using SiteGround Optimizer!', 'sg-cachepress' ),
	__( 'Help other people speed up their sites by rating our plugin.', 'sg-cachepress' ),
	__( 'Environment settings', 'sg-cachepress' ),
	__( 'Fix Insecure Content', 'sg-cachepress' ),
	__( 'Enable this option in case you’re getting insecure content errors on your website. We will dynamically rewrite insecure requests for resources coming from your site.', 'sg-cachepress' ),
	__( 'This feature only works if you have HTTPS Enforce enabled. To start using this feature, enable HTTPS enforce first.', 'sg-cachepress' ),
	__( 'GZIP Compression', 'sg-cachepress' ),
	__( "Enables compression of the content that's delivered to your visitors' browsers improving the network loading times of your site.", 'sg-cachepress' ),
	__( 'Browser Caching', 'sg-cachepress' ),
	__( "Adds rules to store the static content of your site longer in the visitors' browser cache which improves the site performance.", 'sg-cachepress' ),
	__( 'WordPress Heartbeat Optimization', 'sg-cachepress' ),
	__( "The WordPress Heartbeat API checks your post edit pages every 15 seconds and your dashboard and front end every 60 seconds, even in the absence of scheduled tasks. This can generate high CPU usage if you leave browser tabs in which you're logged to WordPress opened for a longer period of time. You can modify these settings to reduce load.", 'sg-cachepress' ),
	__( 'WordPress Admin Pages', 'sg-cachepress' ),
	__( 'Unless you rely on it to execute scheduled tasks, we recommend to keep it disabled.', 'sg-cachepress' ),
	__( 'Posts and Pages', 'sg-cachepress' ),
	__( 'We recommend that you keep it enabled at 180 seconds.', 'sg-cachepress' ),
	__( 'Site Frontend', 'sg-cachepress' ),
	__( 'Unless you rely on it to execute scheduled tasks, we recommend to keep it disabled.', 'sg-cachepress' ),
	__( 'Scheduled Database Maintenance', 'sg-cachepress' ),
	__( 'This functionality will clean up your database {{strong}}once a week{{/strong}} to keep it small and optimized by performing the following tasks:', 'sg-cachepress' ),
	__( 'Perform Database Optimization for MyISAM tables', 'sg-cachepress' ),
	__( 'Delete all automatically created post and page drafts', 'sg-cachepress' ),
	__( 'Delete all page and post revisions', 'sg-cachepress' ),
	__( 'Delete all posts and pages in your Trash', 'sg-cachepress' ),
	__( 'Delete all comments marked as Spam', 'sg-cachepress' ),
	__( 'Delete all expired Transients', 'sg-cachepress' ),
	__( 'Manage External Domains', 'sg-cachepress' ),
	__( 'HTTPS Enforce', 'sg-cachepress' ),
	__( 'Configures your site to work correctly via HTTPS and forces a secure connection to your site. In order to force HTTPS, we will automatically update your database replacing all insecure links. In addition to that, we will add a rule in your .htaccess file, forcing all requests to go through encrypted connection.', 'sg-cachepress' ),
	__( 'You Will be Logged Out', 'sg-cachepress' ),
	__( 'Enabling HTTPS Enforce will have you logged out from your current session and you will have to log back in to your WordPress admin.', 'sg-cachepress' ),
	__( 'Are you sure you wish to proceed?', 'sg-cachepress' ),
	__( 'Combine CSS Files', 'sg-cachepress' ),
	__( 'Combine multiple CSS files into one to lower the number of requests your site generates.', 'sg-cachepress' ),
	__( 'Exclude from CSS Combination', 'sg-cachepress' ),
	__( '%(number)s scripts', 'sg-cachepress' ),
	__( 'Exclude from CSS Combination', 'sg-cachepress' ),
	__( 'Exclude from CSS Minification', 'sg-cachepress' ),
	__( '%(number)s scripts', 'sg-cachepress' ),
	__( 'Exclude from CSS Minification', 'sg-cachepress' ),
	__( 'Minify CSS Files', 'sg-cachepress' ),
	__( 'Minify your CSS files in order to reduce their size and the number of requests on the server.', 'sg-cachepress' ),
	__( 'Preload Combined CSS', 'sg-cachepress' ),
	__( 'Adds the preload value to the combine css files instructing the browser that this is important resource which will be needed very soon to render the page.', 'sg-cachepress' ),
	__( 'This feature only works if you have Combine CSS Files enabled. To start using this feature, enable Combine CSS Files first.', 'sg-cachepress' ),
	__( 'Manage CSS Frontend', 'sg-cachepress' ),
	__( 'Manage JavaScript Frontend', 'sg-cachepress' ),
	__( 'Manage General Frontend', 'sg-cachepress' ),
	__( 'Disable Emojis', 'sg-cachepress' ),
	__( 'Enable to prevent WordPress from automatically detecting and generating emojis in your pages.', 'sg-cachepress' ),
	__( 'Exclude from HTML Minification', 'sg-cachepress' ),
	__( '%(number)s scripts', 'sg-cachepress' ),
	__( 'Exclude from HTML Minification', 'sg-cachepress' ),
	__( 'Fonts Preloading', 'sg-cachepress' ),
	__( "Preload the fonts you're using for faster rendering and better site performance. Make sure you preload only the fonts that are actually in use. {{strong}}Use the full URL to the font.{{/strong}}", 'sg-cachepress' ),
	__( '%(number)s fonts', 'sg-cachepress' ),
	__( 'Fonts to be Preloaded', 'sg-cachepress' ),
	__( 'Minify the HTML Output', 'sg-cachepress' ),
	__( 'Remove unnecessary characters from your HTML output to reduce data size and improve your site loading speed.', 'sg-cachepress' ),
	__( 'Remove Query Strings from Static Resources', 'sg-cachepress' ),
	__( 'Removes version query strings from your static resources improving the caching of those resources.', 'sg-cachepress' ),
	__( 'Web Fonts Optimization', 'sg-cachepress' ),
	__( "With this optimization we're changing the default way to load Google fonts in order to save HTTP requests. In addition to that, all other fonts that your website uses will be properly preloaded so browsers take the least possible amount of time to cache and render them.", 'sg-cachepress' ),
	__( 'Combine JavaScript Files', 'sg-cachepress' ),
	__( 'Combine multiple JavaScript files into one to lower the number of requests your site generates.', 'sg-cachepress' ),
	__( 'Defer Render-blocking JavaScript', 'sg-cachepress' ),
	__( 'Defer loading of render-blocking JavaScript files for faster initial site load.', 'sg-cachepress' ),
	__( 'Exclude from Deferral of Render-blocking JS', 'sg-cachepress' ),
	__( '%(number)s scripts', 'sg-cachepress' ),
	__( 'Exclude from Deferral of Render-blocking JS', 'sg-cachepress' ),
	__( 'Exclude from JavaScript Combination', 'sg-cachepress' ),
	__( '%(number)s scripts', 'sg-cachepress' ),
	__( 'Exclude from JavaScript Combination', 'sg-cachepress' ),
	__( 'Exclude from JavaScript Minification', 'sg-cachepress' ),
	__( '%(number)s scripts', 'sg-cachepress' ),
	__( 'Exclude from JavaScript Minification', 'sg-cachepress' ),
	__( 'Minify JavaScript Files', 'sg-cachepress' ),
	__( 'Minify your JavaScript files in order to reduce their size and the number of requests on the server.', 'sg-cachepress' ),
	__( 'Exclude CSS Classes from Lazy Load', 'sg-cachepress' ),
	__( 'Exclude CSS Classes from Lazy Load', 'sg-cachepress' ),
	__( '%(number)s classes', 'sg-cachepress' ),
	__( 'Exclude Media Types from Lazy Load', 'sg-cachepress' ),
	__( 'Exclude Media Types from Lazy Load', 'sg-cachepress' ),
	__( '%(number)s media types', 'sg-cachepress' ),
	__( 'Configure Image Compression', 'sg-cachepress' ),
	__( 'Select the compression level you wish to use. The higher the compression, the larger the space saved.', 'sg-cachepress' ),
	__( 'Compression Level', 'sg-cachepress' ),
	__( 'Back up all original images.', 'sg-cachepress' ),
	__( 'While this is great to have if you plan to change image compression levels in future, bear in mind that this is a resource consuming option that will take up from your hosting space.', 'sg-cachepress' ),
	__( 'I want to compress my existing images, too.', 'sg-cachepress' ),
	__( 'Overwrite images with custom compression level', 'sg-cachepress' ),
	__( 'Changing your compression level will re-generate all existing images. This is a time and resource consuming process that may take awhile, depending on the number and size of your images.', 'sg-cachepress' ),
	__( 'Compressing image %(converted)s of %(total)s...', 'sg-cachepress' ),
	__( 'Image Compression', 'sg-cachepress' ),
	__( 'We will resize your images to decrease the space they occupy and the time needed for each image to load. The dimensions of your images will not change and with our improved resizing algorithm the visual change in quality is practically non-detectable. Changing your compression level will re-generate all existing images, including WebP images. This is a time and resource consuming process that may take awhile depending on the number and size of your images.', 'sg-cachepress' ),
	__( 'Image compression level is', 'sg-cachepress' ),
	__( 'Preview', 'sg-cachepress' ),
	__( 'Edit', 'sg-cachepress' ),
	__( 'Enabled', 'sg-cachepress' ),
	__( 'Disabled', 'sg-cachepress' ),
	__( 'Default', 'sg-cachepress' ),
	__( 'Select from existing', 'sg-cachepress' ),
	__( 'Select Image', 'sg-cachepress' ),
	__( 'Original - %(size)s', 'sg-cachepress' ),
	__( 'Low (25%% size reduction) - %(size)s', 'sg-cachepress' ),
	__( 'Medium (60%% size reduction) - %(size)s', 'sg-cachepress' ),
	__( 'High (85%% size reduction) - %(size)s', 'sg-cachepress' ),
	__( 'Compare Image Compression Level', 'sg-cachepress' ),
	__( 'Close', 'sg-cachepress' ),
	__( 'Preview Image', 'sg-cachepress' ),
	__( 'Compression Level', 'sg-cachepress' ),
	__( 'Lazy Load Media', 'sg-cachepress' ),
	__( 'With Lazy Load enabled only the media in the visible part of the browser will be loaded. This makes loading faster and smoother for longer pages with multiple media items.', 'sg-cachepress' ),
	__( 'Maximum Image Width', 'sg-cachepress' ),
	__( 'If you’re often uploading or using large images on your website, you might want to start resizing images to fit a maximum width. This can reduce the images size up to 80% and dramatically increase loading speed on pages with one or more large images. Enabling this will resize your existing and future images whose width exceeds 2560 px.', 'sg-cachepress' ),
	__( 'Compression Settings', 'sg-cachepress' ),
	__( 'Media Optimization', 'sg-cachepress' ),
	__( 'Converting image %(converted)s of %(total)s...', 'sg-cachepress' ),
	__( 'Use WebP Images', 'sg-cachepress' ),
	__( 'WebP is a next generation image format supported by modern browsers which greatly reduces the size of standard image formats while keeping the same quality. Almost all current browsers work with WebP.', 'sg-cachepress' ),
	__( 'Disable WebP', 'sg-cachepress' ),
	__( 'Enable WebP', 'sg-cachepress' ),
	__( 'Deactivating the use of WebP images will delete all currently generated WebP files. We will regenerate them again if you enable the option.', 'sg-cachepress' ),
	__( 'Enabling WebP will re-generate all existing WebP images, if any and will generate new WebP versions of all existing standard images. This is a time and resource consuming process that may take awhile, depending on the number and size of your images.', 'sg-cachepress' ),
	__( 'Device Type', 'sg-cachepress' ),
	__( 'Desktop', 'sg-cachepress' ),
	__( 'Mobile', 'sg-cachepress' ),
	__( 'URL', 'sg-cachepress' ),
	__( 'Analyze', 'sg-cachepress' ),
	__( 'CSS Optimizations', 'sg-cachepress' ),
	__( 'JavaScript Optimizations', 'sg-cachepress' ),
	__( 'General Optimizations', 'sg-cachepress' ),
	__( 'Other', 'sg-cachepress' ),
	__( 'Optimize Resources', 'sg-cachepress' ),
	__( 'Potential Saving', 'sg-cachepress' ),
	__( 'URL Address', 'sg-cachepress' ),
	__( 'Transfer Size', 'sg-cachepress' ),
	__( 'Potential Saving', 'sg-cachepress' ),
	__( 'Use WebP Images', 'sg-cachepress' ),
	__( 'WebP is a next generation image format supported by modern browsers which greatly reduces the size of standard image formats while keeping the same quality. Almost all current browsers work with WebP.', 'sg-cachepress' ),
	__( 'Go to media', 'sg-cachepress' ),
	__( 'Recommended Optimizations', 'sg-cachepress' ),
	__( 'Google Score', 'sg-cachepress' ),
	__( 'Page Load Time', 'sg-cachepress' ),
	__( 'Time to First Byte', 'sg-cachepress' ),
	__( 'Either a security plugin, custom function, or rules in your .htaccess file is preventing the WordPress REST API from working properly. SiteGround Optimizer is using it to store its options and other functionalities so please make sure it works properly.', 'sg-cachepress' ),
	__( 'Could not connect to the WordPress REST API', 'sg-cachepress' ),
	__( 'Either a security plugin, custom function or rules in your .htaccess file is preventing the WordPress REST API from working properly. SiteGround Security is using it to store its options and other functionalities so please make sure it works properly.', 'sg-cachepress' ),
	__( 'Could not connect to the WordPress REST API', 'sg-cachepress' ),
	__( 'This field is required.', 'sg-cachepress' ),
	__( 'Invalid URL', 'sg-cachepress' ),
);
/* THIS IS THE END OF THE GENERATED FILE */
